name: bb run tests-emacs
on: [push, pull_request]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          bb: latest
      - name: Install emacs
        uses: purcell/setup-emacs@master
        with:
          version: 29.1

      - name: install buttercup
        run: |-
          set -e
          script=$(cat <<- 'EOF'
            (progn
              (require 'package)
              (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
              (package-initialize)
              (unless (package-installed-p 'buttercup)
                (package-refresh-contents)
                (package-install 'buttercup)))
          EOF
          )
          emacs --batch --eval "$script"

      - run: bb run test:emacs
